### ISSUE TITLE
I'm getting cut off after connecting

### ISSUE THREAD

**Issue by clone45** [twilio-samples/speech-assistant-openai-realtime-api-python#2]
Hello!  I've followed your set up guide but every time I am connected to the AI, I'm cut off.  The Python script is throwing an error:

```
C:\Code\zerojobs\other\max_project\max_plugin\scripts\voice>python main.py
INFO:     Started server process [20004]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
INFO:     54.144.127.116:0 - "POST /incoming-call HTTP/1.1" 200 OK
Client connected
INFO:     ('54.145.78.221', 0) - "WebSocket /media-stream" [accepted]
INFO:     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Bret\anaconda3\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bret\anaconda3\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bret\anaconda3\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\starlette\routing.py", line 93, in app
    await func(session)
  File "C:\Users\Bret\anaconda3\Lib\site-packages\fastapi\routing.py", line 383, in app
    await dependant.call(**solved_result.values)
  File "C:\Code\zerojobs\other\max_project\max_plugin\scripts\voice\main.py", line 60, in handle_media_stream
    async with websockets.connect(
  File "C:\Users\Bret\anaconda3\Lib\site-packages\websockets\legacy\client.py", line 635, in __aenter__
    return await self
           ^^^^^^^^^^
  File "C:\Users\Bret\anaconda3\Lib\site-packages\websockets\legacy\client.py", line 656, in __await_impl__
    await protocol.handshake(
  File "C:\Users\Bret\anaconda3\Lib\site-packages\websockets\legacy\client.py", line 322, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.legacy.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 403
INFO:     connection closed

Any help would be much appreciated.  I'm seeing connections coming into ngrok just fine:


19:03:47.052 PDT GET  /media-stream             101 Switching Protocols                                                 
19:03:36.547 PDT POST /incoming-call            200 OK

**Comment by ronidas39** [comment]
Same issue i am also facing

**Comment by clone45** [comment]
@divyakr-06 I don't know this for certain, but it might be that we don't have access to the new model yet.  

- https://www.reddit.com/r/OpenAI/comments/1fu845b/where_is_the_gpt4orealtimepreview20241001_model/
- https://www.perplexity.ai/search/is-gpt-4o-realtime-preview-ava-U29meUu8TOK8VwS6kcvs9Q

**Comment by divyakr-06** [comment]
@clone45 - yes thats my conclusion too. Also I had to by pass SSL on my local to hit 403 which I believe no access to realtime API yet!

**Comment by genesis-gh-jlangseth** [comment]
working for me now

**Comment by divyakr-06** [comment]
Yes worked for me as well!

**Comment by pkamp3** [comment]
Fixed with Realtime API access rollout.
